  SUBROUTINE HANDLE_ERR(STATUS, LINE)
    USE netcdf
    INTEGER, INTENT(IN) :: STATUS, LINE
    PRINT *, "ERROR: EXITING WITH STATUS ", STATUS, " AT ", LINE
    print *, NF90_STRERROR(status)
!   STOP STATUS
  END SUBROUTINE HANDLE_ERR