SUBROUTINE HANDLE_ERR(STATUS, LINE)
  use netcdf, only: nf90_strerror
  INTEGER, INTENT(IN) :: STATUS, LINE

  PRINT *, "ERROR: EXITING WITH STATUS ", STATUS, "AT LINE ", LINE
  print *, nf90_strerror(status)
  STOP STATUS
END SUBROUTINE HANDLE_ERR
