  SUBROUTINE WNLSM(W,MDW,MME,MA,N,L,PRGOPT,X,RNORM,MODE,IPIVOT, &
                   ITYPE,WD,H,SCALE,Z,TEMP,D)
!***BEGIN PROLOGUE  WNLSM
!***REFER TO  WNNLS
!
!     This is a companion subprogram to WNNLS( ).
!     The documentation for WNNLS( ) has more complete
!     usage instructions.
!
!     Written by Karen H. Haskell, Sandia Laboratories,
!     with the help of R.J. Hanson, Sandia Laboratories,
!     December 1976 - January 1978.
!     Revised March 4, 1982.
!
!     In addition to the parameters discussed in the prologue to
!     subroutine WNNLS, the following work arrays are used in
!     subroutine WNLSM  (they are passed through the calling
!     sequence from WNNLS for purposes of variable dimensioning).
!     Their contents will in general be of no interest to the user.
!
!         IPIVOT(*)
!            An array of length N.  Upon completion it contains the
!         pivoting information for the cols of W(*,*).
!
!         ITYPE(*)
!            An array of length M which is used to keep track
!         of the classification of the equations.  ITYPE(I)=0
!         denotes equation I as an equality constraint.
!         ITYPE(I)=1 denotes equation I as a least squares
!         equation.
!
!         WD(*)
!            An array of length N.  Upon completion it contains the
!         dual solution vector.
!
!         H(*)
!            An array of length N.  Upon completion it contains the
!         pivot scalars of the Householder transformations performed
!         in the case KRANK.LT.L.
!
!         SCALE(*)
!            An array of length M which is used by the subroutine
!         to store the diagonal matrix of weights.
!         These are used to apply the modified Givens
!         transformations.
!
!         Z(*),TEMP(*)
!            Working arrays of length N.
!
!         D(*)
!            An array of length N that contains the
!         column scaling for the matrix (E).
!                                       (A)
!***ROUTINES CALLED  H12,ISAMAX,SASUM,SAXPY,SCOPY,SNRM2,SROTM,SROTMG,
!                    SSCAL,SSWAP,WNLIT,XERROR
!***END PROLOGUE  WNLSM
!
!     THE EDITING REQUIRED TO CONVERT THIS SUBROUTINE FROM SINGLE TO
!     DOUBLE PRECISION INVOLVES THE FOLLOWING CHARACTER STRING CHANGES.
!     USE AN EDITING COMMAND (CHANGE) /STRING-1/(TO)STRING-2/.
!     (BEGIN CHANGES AT LINE WITH C++ IN COLS. 1-3.)
!     /REAL (12 BLANKS)/DOUBLE PRECISION/,/SASUM/DASUM/,/SROTMG/DROTMG/,
!     /SNRM2/DNRM2/,/ SQRT/ DSQRT/,/SROTM/DROTM/,/AMAX1/DMAX1/,
!     /SCOPY/DCOPY/,/SSCAL/DSCAL/,/SAXPY/DAXPY/,/E0/D0/,/SSWAP/DSWAP/,
!     /ISAMAX/IDAMAX/,/SRELPR/DRELPR/
!
!     SUBROUTINE WNLSM (W,MDW,MME,MA,N,L,PRGOPT,X,RNORM,MODE,
!    1                  IPIVOT,ITYPE,WD,H,SCALE,Z,TEMP,D)
!++
    REAL W(MDW,N+1), X(N), H(1), SCALE(MA+MME)
    REAL(kind=16) WD(N)
    REAL DOPE(4)
    REAL Z(1), TEMP(1), PRGOPT(1), D(N), SPARAM(5)
    REAL ALAMDA, ALPHA, ALSQ, AMAX, BNORM, EANORM
    REAL SRELPR, FAC, ONE, BLOWUP
    REAL RNORM, SM, T, TAU, TWO, WMAX, ZERO, ZZ, Z2
    REAL AMAX1, SQRT, SNRM2, SASUM
    INTEGER IPIVOT(MA+MME), ITYPE(MA+MME), ISAMAX, IDOPE(8)
    LOGICAL HITCON, FEASBL, DONE, POS
    DATA ZERO /0.E0/, ONE /1.E0/, TWO /2.E0/, SRELPR /0.E0/
!
!     INITIALIZE-VARIABLES
!***FIRST EXECUTABLE STATEMENT  WNLSM
    IGO998 = 1
    ! IGO998 = 10
    GO TO 180
!
!     PERFORM INITIAL TRIANGULARIZATION IN THE SUBMATRIX
!     CORRESPONDING TO THE UNCONSTRAINED VARIABLES USING
!     THE PROCEDURE INITIALLY-TRIANGULARIZE.
!    10 IGO995 = 20
10  IGO995 = 1
    GO TO 280
!
!     PERFORM WNNLS ALGORITHM USING THE FOLLOWING STEPS.
!
!     UNTIL(DONE)
!
!        COMPUTE-SEARCH-DIRECTION-AND-FEASIBLE-POINT
!
!        WHEN (HITCON) ADD-CONSTRAINTS
!
!        ELSE PERFORM-MULTIPLIER-TEST-AND-DROP-A-CONSTRAINT
!
!        FIN
!
!     COMPUTE-FINAL-SOLUTION
!
20  IF (DONE) GO TO 80
!
    IGO991 = 30
    GO TO 300
!
!     COMPUTE-SEARCH-DIRECTION-AND-FEASIBLE-POINT
!
30  IF (.NOT.(HITCON)) GO TO 50
    IGO986 = 40
    GO TO 370
40  GO TO 70
!
!     WHEN (HITCON) ADD-CONSTRAINTS
!
50  IGO983 = 60
    GO TO 640
60  CONTINUE
!
!     ELSE PERFORM-MULTIPLIER-TEST-AND-DROP-A-CONSTRAINT
!
70  GO TO 20
!
80  IGO980 = 1
!   80 IGO980 = 90
    GO TO 1000
!
!     COMPUTE-FINAL-SOLUTION
!
90  RETURN
100 CONTINUE
!
!     TO PROCESS-OPTION-VECTOR
    FAC = 1.E-4
!
!     THE NOMINAL TOLERANCE USED IN THE CODE,
    TAU = SQRT(SRELPR)
!
!     THE NOMINAL BLOW-UP FACTOR USED IN THE CODE.
    BLOWUP = TAU
!
!     THE NOMINAL COLUMN SCALING USED IN THE CODE IS
!     THE IDENTITY SCALING.
    D(1) = ONE
    CALL SCOPY(N, D, 0, D, 1)
!
!     DEFINE BOUND FOR NUMBER OF OPTIONS TO CHANGE.
    NOPT = 1000
!
!     DEFINE BOUND FOR POSITIVE VALUE OF LINK.
    NLINK = 100000
    NTIMES = 0
    LAST = 1
    LINK = PRGOPT(1)
    IF (.NOT.(LINK.LE.0 .OR. LINK.GT.NLINK)) GO TO 110
    NERR = 3
    IOPT = 1
    CALL XERROR( 'WNNLS( ) THE OPTION VECTOR IS UNDEFINED', 39, NERR, IOPT)
    MODE = 2
    RETURN
110 IF (.NOT.(LINK.GT.1)) GO TO 160
    NTIMES = NTIMES + 1
    IF (.NOT.(NTIMES.GT.NOPT)) GO TO 120
    NERR = 3
    IOPT = 1
    CALL XERROR( 'WNNLS( ). THE LINKS IN THE OPTION VECTOR ARE CYCLING.', 53, NERR, IOPT)
    MODE = 2
    RETURN
120 KEY = PRGOPT(LAST+1)
    IF (.NOT.(KEY.EQ.6 .AND. PRGOPT(LAST+2).NE.ZERO)) GO TO 140
    DO 130 J=1,N
      T = SNRM2(M,W(1,J),1)
      IF (T.NE.ZERO) T = ONE/T
      D(J) = T
130 CONTINUE
140 IF (KEY.EQ.7) CALL SCOPY(N, PRGOPT(LAST+2), 1, D, 1)
    IF (KEY.EQ.8) TAU = AMAX1(SRELPR,PRGOPT(LAST+2))
    IF (KEY.EQ.9) BLOWUP = AMAX1(SRELPR,PRGOPT(LAST+2))
    NEXT = PRGOPT(LINK)
    IF (.NOT.(NEXT.LE.0 .OR. NEXT.GT.NLINK)) GO TO 150
    NERR = 3
    IOPT = 1
    CALL XERROR( 'WNNLS( ) THE OPTION VECTOR IS UNDEFINED', 39, NERR,IOPT)
    MODE = 2
    RETURN
150 LAST = LINK
    LINK = NEXT
    GO TO 110
160 DO 170 J=1,N
      CALL SSCAL(M, D(J), W(1,J), 1)
170 CONTINUE
    GO TO 1260
180 CONTINUE
!
!     TO INITIALIZE-VARIABLES
!
!     SRELPR IS THE PRECISION FOR THE PARTICULAR MACHINE
!     BEING USED.  THIS LOGIC AVOIDS RECOMPUTING IT EVERY ENTRY.
    IF (.NOT.(SRELPR.EQ.ZERO)) GO TO 210
!*** changed back by BROSS
!*** changed by RF Boisvert, 19-Feb-92  (fails on HP 9000 Series 300)
!ross      srelpr = r1mach(4)
    SRELPR = ONE
190 IF (ONE+SRELPR.EQ.ONE) GO TO 200
    SRELPR = SRELPR/TWO
    GO TO 190
200 SRELPR = SRELPR*TWO
!ross
210 M = MA + MME
    ME = MME
    MEP1 = ME + 1
    ! IGO977 = 220
    IGO977 = 1
    GO TO 100
!
!     PROCESS-OPTION-VECTOR
220 DONE = .FALSE.
    ITER = 0
    ITMAX = 3*(N-L)
    MODE = 0
    LP1 = L + 1
    NSOLN = L
    NSP1 = NSOLN + 1
    NP1 = N + 1
    NM1 = N - 1
    L1 = MIN0(M,L)
!
!     COMPUTE SCALE FACTOR TO APPLY TO EQUAL. CONSTRAINT EQUAS.
    DO 230 J=1,N
      WD(J) = SASUM(M,W(1,J),1)
230 CONTINUE
    IMAX = ISAMAX(N,WD,1)
    EANORM = WD(IMAX)
    BNORM = SASUM(M,W(1,NP1),1)
    ALAMDA = EANORM/(SRELPR*FAC)
!
!     DEFINE SCALING DIAG MATRIX FOR MOD GIVENS USAGE AND
!     CLASSIFY EQUATION TYPES.
    ALSQ = ALAMDA**2
    DO 260 I=1,M
!
!     WHEN EQU I IS HEAVILY WEIGHTED ITYPE(I)=0, ELSE ITYPE(I)=1.
      IF (.NOT.(I.LE.ME)) GO TO 240
      T = ALSQ
      ITEMP = 0
      GO TO 250
240   T = ONE
      ITEMP = 1
250   SCALE(I) = T
      ITYPE(I) = ITEMP
260 CONTINUE
!
!     SET THE SOLN VECTOR X(*) TO ZERO AND THE COL INTERCHANGE
!     MATRIX TO THE IDENTITY.
    X(1) = ZERO
    CALL SCOPY(N, X, 0, X, 1)
    DO 270 I=1,N
      IPIVOT(I) = I
270 CONTINUE
    GO TO 1230
280 CONTINUE
!
!     TO INITIALLY-TRIANGULARIZE
!
!     SET FIRST L COMPS. OF DUAL VECTOR TO ZERO BECAUSE
!     THESE CORRESPOND TO THE UNCONSTRAINED VARIABLES.
    IF (.NOT.(L.GT.0)) GO TO 290
    WD(1) = ZERO
    CALL SCOPY(L, WD, 0, WD, 1)
!
!     THE ARRAYS IDOPE(*) AND DOPE(*) ARE USED TO PASS
!     INFORMATION TO WNLIT().  THIS WAS DONE TO AVOID
!     A LONG CALLING SEQUENCE OR THE USE OF COMMON.
290 IDOPE(1) = ME
    IDOPE(2) = MEP1
    IDOPE(3) = 0
    IDOPE(4) = 1
    IDOPE(5) = NSOLN
    IDOPE(6) = 0
    IDOPE(7) = 1
    IDOPE(8) = L1
!
    DOPE(1) = ALSQ
    DOPE(2) = EANORM
    DOPE(3) = FAC
    DOPE(4) = TAU
    CALL WNLIT(W, MDW, M, N, L, IPIVOT, ITYPE, H, SCALE, RNORM,IDOPE, DOPE, DONE)
    ME = IDOPE(1)
    MEP1 = IDOPE(2)
    KRANK = IDOPE(3)
    KRP1 = IDOPE(4)
    NSOLN = IDOPE(5)
    NIV = IDOPE(6)
    NIV1 = IDOPE(7)
    L1 = IDOPE(8)
    GO TO 1240
300 CONTINUE
!
!     TO COMPUTE-SEARCH-DIRECTION-AND-FEASIBLE-POINT
!
!     SOLVE THE TRIANGULAR SYSTEM OF CURRENTLY NON-ACTIVE
!     VARIABLES AND STORE THE SOLUTION IN Z(*).
!
!     SOLVE-SYSTEM
    IGO958 = 1
    ! IGO958 = 310
    GO TO 1110
!
!     INCREMENT ITERATION COUNTER AND CHECK AGAINST MAX. NUMBER
!     OF ITERATIONS.
310 ITER = ITER + 1
    IF (.NOT.(ITER.GT.ITMAX)) GO TO 320
    MODE = 1
    DONE = .TRUE.
!
!     CHECK TO SEE IF ANY CONSTRAINTS HAVE BECOME ACTIVE.
!     IF SO, CALCULATE AN INTERPOLATION FACTOR SO THAT ALL
!     ACTIVE CONSTRAINTS ARE REMOVED FROM THE BASIS.
320 ALPHA = TWO
    HITCON = .FALSE.
    IF (.NOT.(L.LT.NSOLN)) GO TO 360
      ! print *, 'LP1=', LP1
      ! print *, 'NSOLN=', NSOLN
    DO 350 J=LP1,NSOLN
      ZZ = Z(J)
      IF (.NOT.(ZZ.LE.ZERO)) GO TO 340
      T = X(J)/(X(J)-ZZ)
      IF (.NOT.(T.LT.ALPHA)) GO TO 330
      ALPHA = T
      JCON = J
330   HITCON = .TRUE.
340   CONTINUE
350 CONTINUE
360 GO TO 1220
370 CONTINUE
!
!     TO ADD-CONSTRAINTS
!
!     USE COMPUTED ALPHA TO INTERPOLATE BETWEEN LAST
!     FEASIBLE SOLUTION X(*) AND CURRENT UNCONSTRAINED
!     (AND INFEASIBLE) SOLUTION Z(*).
    IF (.NOT.(LP1.LE.NSOLN)) GO TO 390
    DO 380 J=LP1,NSOLN
      X(J) = X(J) + ALPHA*(Z(J)-X(J))
380 CONTINUE
390 FEASBL = .FALSE.
    GO TO 410
400 IF (FEASBL) GO TO 610
!
!     REMOVE COL JCON AND SHIFT COLS JCON+1 THROUGH N TO THE
!     LEFT. SWAP COL JCON INTO THE N-TH POSITION.  THIS ACHIEVES
!     UPPER HESSENBERG FORM FOR THE NONACTIVE CONSTRAINTS AND
!     LEAVES AN UPPER HESSENBERG MATRIX TO RETRIANGULARIZE.
410 DO 420 I=1,M
      T = W(I,JCON)
      CALL SCOPY(N-JCON, W(I,JCON+1), MDW, W(I,JCON), MDW)
      W(I,N) = T
420 CONTINUE
!
!     UPDATE PERMUTED INDEX VECTOR TO REFLECT THIS SHIFT AND SWAP.
    ITEMP = IPIVOT(JCON)
    IF (.NOT.(JCON.LT.N)) GO TO 440
    DO 430 I=JCON,NM1
      IPIVOT(I) = IPIVOT(I+1)
430 CONTINUE
440 IPIVOT(N) = ITEMP
!
!     SIMILARLY REPERMUTE X(*) VECTOR.
    CALL SCOPY(N-JCON, X(JCON+1), 1, X(JCON), 1)
    X(N) = ZERO
    NSP1 = NSOLN
    NSOLN = NSOLN - 1
    NIV1 = NIV
    NIV = NIV - 1
!
!     RETRIANGULARIZE UPPER HESSENBERG MATRIX AFTER ADDING CONSTRAINTS.
    J = JCON
    I = KRANK + JCON - L
450 IF (.NOT.(J.LE.NSOLN)) GO TO 570
    IF (.NOT.(ITYPE(I).EQ.0 .AND. ITYPE(I+1).EQ.0)) GO TO 470
    IGO938 = 460
    GO TO 620
!
!     (ITYPE(I).EQ.0 .AND. ITYPE(I+1).EQ.0) ZERO-IP1-TO-I-IN-COL-J
460 GO TO 560
470 IF (.NOT.(ITYPE(I).EQ.1 .AND. ITYPE(I+1).EQ.1)) GO TO 490
    IGO938 = 480
    GO TO 620
!
!     (ITYPE(I).EQ.1 .AND. ITYPE(I+1).EQ.1) ZERO-IP1-TO-I-IN-COL-J
480 GO TO 560
490 IF (.NOT.(ITYPE(I).EQ.1 .AND. ITYPE(I+1).EQ.0)) GO TO 510
    CALL SSWAP(NP1, W(I,1), MDW, W(I+1,1), MDW)
    CALL SSWAP(1, SCALE(I), 1, SCALE(I+1), 1)
    ITEMP = ITYPE(I+1)
    ITYPE(I+1) = ITYPE(I)
    ITYPE(I) = ITEMP
!
!     SWAPPED ROW WAS FORMERLY A PIVOT ELT., SO IT WILL
!     BE LARGE ENOUGH TO PERFORM ELIM.
    IGO938 = 500
    GO TO 620
!
!     ZERO-IP1-TO-I-IN-COL-J
500 GO TO 560
510 IF (.NOT.(ITYPE(I).EQ.0 .AND. ITYPE(I+1).EQ.1)) GO TO 550
    T = SCALE(I)*W(I,J)**2/ALSQ
    IF (.NOT.(T.GT.TAU**2*EANORM**2)) GO TO 530
    IGO938 = 520
    GO TO 620
520 GO TO 540
530 CALL SSWAP(NP1, W(I,1), MDW, W(I+1,1), MDW)
    CALL SSWAP(1, SCALE(I), 1, SCALE(I+1), 1)
    ITEMP = ITYPE(I+1)
    ITYPE(I+1) = ITYPE(I)
    ITYPE(I) = ITEMP
    W(I+1,J) = ZERO
540 CONTINUE
550 CONTINUE
560 I = I + 1
    J = J + 1
    GO TO 450
!
!     SEE IF THE REMAINING COEFFS IN THE SOLN SET ARE FEASIBLE.  THEY
!     SHOULD BE BECAUSE OF THE WAY ALPHA WAS DETERMINED.  IF ANY ARE
!     INFEASIBLE IT IS DUE TO ROUNDOFF ERROR.  ANY THAT ARE NON-
!     POSITIVE WILL BE SET TO ZERO AND REMOVED FROM THE SOLN SET.
570 IF (.NOT.(LP1.LE.NSOLN)) GO TO 590
    DO 580 JCON=LP1,NSOLN
      IF (X(JCON).LE.ZERO) GO TO 600
580 CONTINUE
590 FEASBL = .TRUE.
600 CONTINUE
    GO TO 400
610 GO TO 1200
620 CONTINUE
!
!     TO ZERO-IP1-TO-I-IN-COL-J
    IF (.NOT.(W(I+1,J).NE.ZERO)) GO TO 630
    CALL SROTMG(SCALE(I), SCALE(I+1), W(I,J), W(I+1,J), SPARAM)
    W(I+1,J) = ZERO
    CALL SROTM(NP1-J, W(I,J+1), MDW, W(I+1,J+1), MDW, SPARAM)
630 GO TO 1290
640 CONTINUE
!
!     TO PERFORM-MULTIPLIER-TEST-AND-DROP-A-CONSTRAINT
    CALL SCOPY(NSOLN, Z, 1, X, 1)
    IF (.NOT.(NSOLN.LT.N)) GO TO 650
    X(NSP1) = ZERO
    CALL SCOPY(N-NSOLN, X(NSP1), 0, X(NSP1), 1)
650 I = NIV1
660 IF (.NOT.(I.LE.ME)) GO TO 690
!
!     RECLASSIFY LEAST SQUARES EQATIONS AS EQUALITIES AS
!     NECESSARY.
    IF (.NOT.(ITYPE(I).EQ.0)) GO TO 670
    I = I + 1
    GO TO 680
670 CALL SSWAP(NP1, W(I,1), MDW, W(ME,1), MDW)
    CALL SSWAP(1, SCALE(I), 1, SCALE(ME), 1)
    ITEMP = ITYPE(I)
    ITYPE(I) = ITYPE(ME)
    ITYPE(ME) = ITEMP
    MEP1 = ME
    ME = ME - 1
680 GO TO 660
!
!     FORM INNER PRODUCT VECTOR WD(*) OF DUAL COEFFS.
690 IF (.NOT.(NSP1.LE.N)) GO TO 730
    DO 720 J=NSP1,N
      SM = ZERO
      IF (.NOT.(NSOLN.LT.M)) GO TO 710
      DO 700 I=NSP1,M
        SM = SM + SCALE(I)*W(I,J)*W(I,NP1)
700   CONTINUE
710   WD(J) = SM
720 CONTINUE
730 GO TO 750
740 IF (POS .OR. DONE) GO TO 970
!
!     FIND J SUCH THAT WD(J)=WMAX IS MAXIMUM.  THIS DETERMINES
!     THAT THE INCOMING COL J WILL REDUCE THE RESIDUAL VECTOR
!     AND BE POSITIVE.
750 WMAX = ZERO
    IWMAX = NSP1
    IF (.NOT.(NSP1.LE.N)) GO TO 780
    DO 770 J=NSP1,N
      IF (.NOT.(WD(J).GT.WMAX)) GO TO 760
      WMAX = WD(J)
      IWMAX = J
760   CONTINUE
770 CONTINUE
780 IF (.NOT.(WMAX.LE.ZERO)) GO TO 790
    DONE = .TRUE.
    GO TO 960
!
!     SET DUAL COEFF TO ZERO FOR INCOMING COL.
790 WD(IWMAX) = ZERO
!
!     WMAX .GT. ZERO, SO OKAY TO MOVE COL IWMAX TO SOLN SET.
!     PERFORM TRANSFORMATION TO RETRIANGULARIZE, AND TEST
!     FOR NEAR LINEAR DEPENDENCE.
!     SWAP COL IWMAX INTO NSOLN-TH POSITION TO MAINTAIN UPPER
!     HESSENBERG FORM OF ADJACENT COLS, AND ADD NEW COL TO
!     TRIANGULAR DECOMPOSITION.
    NSOLN = NSP1
    NSP1 = NSOLN + 1
    NIV = NIV1
    NIV1 = NIV + 1
    IF (.NOT.(NSOLN.NE.IWMAX)) GO TO 800
    CALL SSWAP(M, W(1,NSOLN), 1, W(1,IWMAX), 1)
    WD(IWMAX) = WD(NSOLN)
    WD(NSOLN) = ZERO
    ITEMP = IPIVOT(NSOLN)
    IPIVOT(NSOLN) = IPIVOT(IWMAX)
    IPIVOT(IWMAX) = ITEMP
!
!     REDUCE COL NSOLN SO THAT THE MATRIX OF NONACTIVE
!     CONSTRAINTS VARIABLES IS TRIANGULAR.
800 J = M
810 IF (.NOT.(J.GT.NIV)) GO TO 870
    JM1 = J - 1
    JP = JM1
!
!     WHEN OPERATING NEAR THE ME LINE, TEST TO SEE IF THE PIVOT ELT.
!     IS NEAR ZERO.  IF SO, USE THE LARGEST ELT. ABOVE IT AS THE PIVOT.
!     THIS IS TO MAINTAIN THE SHARP INTERFACE BETWEEN WEIGHTED AND
!     NON-WEIGHTED ROWS IN ALL CASES.
    IF (.NOT.(J.EQ.MEP1)) GO TO 850
    IMAX = ME
    AMAX = SCALE(ME)*W(ME,NSOLN)**2
820 IF (.NOT.(JP.GE.NIV)) GO TO 840
    T = SCALE(JP)*W(JP,NSOLN)**2
    IF (.NOT.(T.GT.AMAX)) GO TO 830
    IMAX = JP
    AMAX = T
830 JP = JP - 1
    GO TO 820
840 JP = IMAX
850 IF (.NOT.(W(J,NSOLN).NE.ZERO)) GO TO 860
    CALL SROTMG(SCALE(JP), SCALE(J), W(JP,NSOLN), W(J,NSOLN), SPARAM)
    W(J,NSOLN) = ZERO
    CALL SROTM(NP1-NSOLN, W(JP,NSP1), MDW, W(J,NSP1), MDW, SPARAM)
860 J = JM1
    GO TO 810
!
!     SOLVE FOR Z(NSOLN)=PROPOSED NEW VALUE FOR X(NSOLN).
!     TEST IF THIS IS NONPOSITIVE OR TOO LARGE.
!     IF THIS WAS TRUE OR IF THE PIVOT TERM WAS ZERO REJECT
!     THE COL AS DEPENDENT.
870 IF (.NOT.(W(NIV,NSOLN).NE.ZERO)) GO TO 890
    ISOL = NIV
    IGO897 = 880
    GO TO 980
!
!     TEST-PROPOSED-NEW-COMPONENT
880 GO TO 940
890 IF (.NOT.(NIV.LE.ME .AND. W(MEP1,NSOLN).NE.ZERO)) GO TO 920
!
!     TRY TO ADD ROW MEP1 AS AN ADDITIONAL EQUALITY CONSTRAINT.
!     CHECK SIZE OF PROPOSED NEW SOLN COMPONENT.
!     REJECT IT IF IT IS TOO LARGE.
    ISOL = MEP1
    IGO897 = 900
    GO TO 980
!
!     TEST-PROPOSED-NEW-COMPONENT
900 IF (.NOT.(POS)) GO TO 910
!
!     SWAP ROWS MEP1 AND NIV, AND SCALE FACTORS FOR THESE ROWS.
    CALL SSWAP(NP1, W(MEP1,1), MDW, W(NIV,1), MDW)
    CALL SSWAP(1, SCALE(MEP1), 1, SCALE(NIV), 1)
    ITEMP = ITYPE(MEP1)
    ITYPE(MEP1) = ITYPE(NIV)
    ITYPE(NIV) = ITEMP
    ME = MEP1
    MEP1 = ME + 1
910 GO TO 930
920 POS = .FALSE.
930 CONTINUE
940 IF (POS) GO TO 950
    NSP1 = NSOLN
    NSOLN = NSOLN - 1
    NIV1 = NIV
    NIV = NIV - 1
950 CONTINUE
960 GO TO 740
970 GO TO 1250
980 CONTINUE
!
!     TO TEST-PROPOSED-NEW-COMPONENT
    Z2 = W(ISOL,NP1)/W(ISOL,NSOLN)
    Z(NSOLN) = Z2
    POS = Z2.GT.ZERO
    IF (.NOT.(Z2*EANORM.GE.BNORM .AND. POS)) GO TO 990
    POS = .NOT.(BLOWUP*Z2*EANORM.GE.BNORM)
990 GO TO 1280
1000 CONTINUE
!     TO COMPUTE-FINAL-SOLUTION
!
!     SOLVE SYSTEM, STORE RESULTS IN X(*).
!
    IGO958 = 2
    ! IGO958 = 1010
    GO TO 1110
!     SOLVE-SYSTEM
1010 CALL SCOPY(NSOLN, Z, 1, X, 1)
!
!     APPLY HOUSEHOLDER TRANSFORMATIONS TO X(*) IF KRANK.LT.L
    IF (.NOT.(0.LT.KRANK .AND. KRANK.LT.L)) GO TO 1030
    DO 1020 I=1,KRANK
      CALL H12(2, I, KRP1, L, W(I,1), MDW, H(I), X, 1, 1, 1)
1020 CONTINUE
!
!     FILL IN TRAILING ZEROES FOR CONSTRAINED VARIABLES NOT IN SOLN.
1030 IF (.NOT.(NSOLN.LT.N)) GO TO 1040
    X(NSP1) = ZERO
    CALL SCOPY(N-NSOLN, X(NSP1), 0, X(NSP1), 1)
!
!     REPERMUTE SOLN VECTOR TO NATURAL ORDER.
1040 DO 1070 I=1,N
       J = I
1050   IF (IPIVOT(J).EQ.I) GO TO 1060
       J = J + 1
       GO TO 1050
1060   IPIVOT(J) = IPIVOT(I)
       IPIVOT(I) = J
       CALL SSWAP(1, X(J), 1, X(I), 1)
1070 CONTINUE
!
!     RESCALE THE SOLN USING THE COL SCALING.
     DO 1080 J=1,N
       X(J) = X(J)*D(J)
1080 CONTINUE
    IF (.NOT.(NSOLN.LT.M)) GO TO 1100
     DO 1090 I=NSP1,M
       T = W(I,NP1)
       IF (I.LE.ME) T = T/ALAMDA
       T = (SCALE(I)*T)*T
       RNORM = RNORM + T
1090 CONTINUE
1100 RNORM = SQRT(RNORM)
    GO TO 1210
!
!     TO SOLVE-SYSTEM
!
1110 CONTINUE
    IF (.NOT.(DONE)) GO TO 1120
    ISOL = 1
    GO TO 1130
1120 ISOL = LP1
1130 IF (.NOT.(NSOLN.GE.ISOL)) GO TO 1190
!
!     COPY RT. HAND SIDE INTO TEMP VECTOR TO USE OVERWRITING METHOD.
    CALL SCOPY(NIV, W(1,NP1), 1, TEMP, 1)
     DO 1180 JJ=ISOL,NSOLN
       J = NSOLN - JJ + ISOL
       IF (.NOT.(J.GT.KRANK)) GO TO 1140
       I = NIV - JJ + ISOL
       GO TO 1150
1140   I = J
1150   IF (.NOT.(J.GT.KRANK .AND. J.LE.L)) GO TO 1160
       Z(J) = ZERO
       GO TO 1170
 1160  Z(J) = TEMP(I)/W(I,J)
       CALL SAXPY(I-1, -Z(J), W(1,J), 1, TEMP, 1)
1170   CONTINUE
1180 CONTINUE
1190 GO TO 1270
1200 GO TO (40) IGO986
1210 GO TO (90) IGO980
1220 GO TO (30) IGO991
1230 GO TO (10) IGO998
1240 GO TO (20) IGO995
1250 GO TO (60) IGO983
1260 GO TO (220) IGO977
1270 GO TO (310, 1010) IGO958
1280 GO TO (880, 900) IGO897
1290 GO TO (460, 480, 500, 520) IGO938
  END SUBROUTINE WNLSM