SUBROUTINE XERPRT(MESSG,NMESSG)
!***BEGIN PROLOGUE  XERPRT
!***DATE WRITTEN   790801   (YYMMDD)
!***REVISION DATE  820801   (YYMMDD)
!***CATEGORY NO.  Z
!***KEYWORDS  ERROR,XERROR PACKAGE
!***AUTHOR  JONES, R. E., (SNLA)
!***PURPOSE  Prints error messages.
!***DESCRIPTION
!     Abstract
!        Print the Hollerith message in MESSG, of length NMESSG,
!        on each file indicated by XGETUA.
!     Latest revision ---  19 MAR 1980
!***REFERENCES  JONES R.E., KAHANER D.K., "XERROR, THE SLATEC ERROR-
!                 HANDLING PACKAGE", SAND82-0800, SANDIA LABORATORIES,
!                 1982.
!***ROUTINES CALLED  I1MACH,S88FMT,XGETUA
!***END PROLOGUE  XERPRT
  IMPLICIT NONE

  CHARACTER*(*), INTENT(IN) :: MESSG
  INTEGER, INTENT(IN) :: NMESSG
  INTEGER, DIMENSION(5) :: LUN
  INTEGER :: NUNIT, LENMES, KUNIT, IUNIT, LAST, ICHAR
!     OBTAIN UNIT NUMBERS AND WRITE LINE TO EACH UNIT
!***FIRST EXECUTABLE STATEMENT  XERPRT
    CALL XGETUA(LUN,NUNIT)
    LENMES = LEN(MESSG)
    DO 20 KUNIT=1,NUNIT
      IUNIT = LUN(KUNIT)
      IF (IUNIT.EQ.0) IUNIT = I1MACH(4)
      DO 10 ICHAR=1,LENMES,72
        LAST = MIN0(ICHAR+71 , LENMES)
        WRITE (IUNIT,'(1X,A)') MESSG(ICHAR:LAST)
10 CONTINUE
20 CONTINUE
  RETURN
END SUBROUTINE XERPRT