  SUBROUTINE XERSAV(MESSG,NMESSG,NERR,LEVEL,ICOUNT)
!***BEGIN PROLOGUE  XERSAV
!***DATE WRITTEN   800319   (YYMMDD)
!***REVISION DATE  820801   (YYMMDD)
!***CATEGORY NO.  Z
!***KEYWORDS  ERROR,XERROR PACKAGE
!***AUTHOR  JONES, R. E., (SNLA)
!***PURPOSE  Records that an error occurred.
!***DESCRIPTION
!     Abstract
!        Record that this error occurred.
!
!     Description of Parameters
!     --Input--
!       MESSG, NMESSG, NERR, LEVEL are as in XERROR,
!       except that when NMESSG=0 the tables will be
!       dumped and cleared, and when NMESSG is less than zero the
!       tables will be dumped and not cleared.
!     --Output--
!       ICOUNT will be the number of times this message has
!       been seen, or zero if the table has overflowed and
!       does not contain this message specifically.
!       When NMESSG=0, ICOUNT will not be altered.
!
!     Written by Ron Jones, with SLATEC Common Math Library Subcommittee
!     Latest revision ---  19 Mar 1980
!***REFERENCES  JONES R.E., KAHANER D.K., "XERROR, THE SLATEC ERROR-
!                 HANDLING PACKAGE", SAND82-0800, SANDIA LABORATORIES,
!                 1982.
!***ROUTINES CALLED  I1MACH,S88FMT,XGETUA
!***END PROLOGUE  XERSAV
    INTEGER LUN(5)
    CHARACTER*(*) MESSG
    CHARACTER*20 MESTAB(10),MES
    DIMENSION NERTAB(10),LEVTAB(10),KOUNT(10)
    SAVE MESTAB,NERTAB,LEVTAB,KOUNT,KOUNTX
!     NEXT TWO DATA STATEMENTS ARE NECESSARY TO PROVIDE A BLANK
!     ERROR TABLE INITIALLY
    DATA KOUNT(1),KOUNT(2),KOUNT(3),KOUNT(4),KOUNT(5), &
         KOUNT(6),KOUNT(7),KOUNT(8),KOUNT(9),KOUNT(10) &
         /0,0,0,0,0,0,0,0,0,0/
    DATA KOUNTX/0/
!***FIRST EXECUTABLE STATEMENT  XERSAV
    IF (NMESSG.GT.0) GO TO 80
!   DUMP THE TABLE
    IF (KOUNT(1).EQ.0) RETURN
!   PRINT TO EACH UNIT
    CALL XGETUA(LUN,NUNIT)
    DO 60 KUNIT=1,NUNIT
      IUNIT = LUN(KUNIT)
      IF (IUNIT.EQ.0) IUNIT = I1MACH(4)
!     PRINT TABLE HEADER
      WRITE (IUNIT,10)
10    FORMAT (32H0          ERROR MESSAGE SUMMARY/ &
              51H MESSAGE START             NERR     LEVEL     COUNT)
!     PRINT BODY OF TABLE
      DO 20 I=1,10
        IF (KOUNT(I).EQ.0) GO TO 30
        WRITE (IUNIT,15) MESTAB(I),NERTAB(I),LEVTAB(I),KOUNT(I)
15      FORMAT (1X,A20,3I10)
20    CONTINUE
30    CONTINUE
!     PRINT NUMBER OF OTHER ERRORS
      IF (KOUNTX.NE.0) WRITE (IUNIT,40) KOUNTX
40    FORMAT (41H0OTHER ERRORS NOT INDIVIDUALLY TABULATED=,I10)
      WRITE (IUNIT,50)
50    FORMAT (1X)
60  CONTINUE
    IF (NMESSG.LT.0) RETURN
!   CLEAR THE ERROR TABLES
    DO 70 I=1,10
70  KOUNT(I) = 0
    KOUNTX = 0
    RETURN
80  CONTINUE
!   PROCESS A MESSAGE...
!   SEARCH FOR THIS MESSG, OR ELSE AN EMPTY SLOT FOR THIS MESSG,
!   OR ELSE DETERMINE THAT THE ERROR TABLE IS FULL.
    MES = MESSG
    DO 90 I=1,10
      II = I
      IF (KOUNT(I).EQ.0) GO TO 110
      IF (MES.NE.MESTAB(I)) GO TO 90
      IF (NERR.NE.NERTAB(I)) GO TO 90
      IF (LEVEL.NE.LEVTAB(I)) GO TO 90
      GO TO 100
90  CONTINUE
!   THREE POSSIBLE CASES...
!   TABLE IS FULL
    KOUNTX = KOUNTX+1
    ICOUNT = 1
    RETURN
!   MESSAGE FOUND IN TABLE
100 KOUNT(II) = KOUNT(II) + 1
    ICOUNT = KOUNT(II)
    RETURN
!   EMPTY SLOT FOUND FOR NEW MESSAGE
110 MESTAB(II) = MES
    NERTAB(II) = NERR
    LEVTAB(II) = LEVEL
    KOUNT(II)  = 1
    ICOUNT = 1
    RETURN
    END SUBROUTINE XERSAV